[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
broadcast = "broadcast"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.optimizer]
enabled = true
runs = 200

[profile.default.model_checker]
contracts = { "src/Quest.sol" = [ "Quest" ], "src/RewardPool.sol" = [ "RewardPool" ] }
engine = "chc"
timeout = 10000
targets = [ "assert" ]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "preserve"

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
base_mainnet = { key = "${ETHERSCAN_API_KEY}" }

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.0.0" }
chainlink = { git = "https://github.com/smartcontractkit/chainlink-brownie-contracts.git", tag = "v1.1.1" }
